"""Update table with new columns

Revision ID: 0d4160cd8c8d
Revises: 3ef6c02006b9
Create Date: 2025-07-11 16:38:51.309987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d4160cd8c8d'
down_revision: Union[str, None] = '3ef6c02006b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_routes')
    op.create_unique_constraint(None, 'channels', ['api_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channels', type_='unique')
    op.create_table('api_routes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('core_api_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cache_key_prefix', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('api_routes_pkey'))
    )
    # ### end Alembic commands ###
