"""Add login_time and token_type columns

Revision ID: 2a5321a3fa5b
Revises: 
Create Date: 2025-05-29 16:02:51.226495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a5321a3fa5b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_api', sa.Column('login_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_api', sa.Column('token_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_api', 'token_type')
    op.drop_column('user_api', 'login_time')
    # ### end Alembic commands ###
